openvpn: remove duplicate attempt to create dir in ${localstatedir}
When systemd is in DISTRO_FEATURES we have two attempts to create
${localstatedir}/run/openvpn: one at build time with install command and
the other via systemd-tmpfiles at runtime which is enabled by installing
openvpn-volatile.conf. Beside looking redundant, by dropping the build-time
dir creation attempt solves the following error when building images with
both base-files and openvpn:

Error: Transaction check error:
  file /var/run conflicts between attempted installs of
  openvpn-2.3.9-r0.cortexa7hf_neon_vfpv4 and
  base-files-3.0.14-r89.raspberrypi3

Signed-off-by: Andrea Galbusera <gizero@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>